services:
  flaskapp:
    image: rizwan192/flaskapp:latest
    expose:
      - 5000
    environment:
      - FLASK_APP=run.py
      - DEBUG=False

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - flaskapp
