version: '3.4'

services:
  flaskdockerstarterkit:
    image: flaskdockerstarterkit
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
    volumes:
      - .:/flask_starterkit:cached
