version: "3.4"

services:
  app:
    image: flaskapp
    build:
      context: .
      dockerfile: ./Dockerfile
      target: production
    ports:
      - 5000:5000
    environment:
      FLASK_APP: run.py
      FLASK_DEBUG: 1

  unit-test-container:
    image: unit-test-container
    build:
      context: .
      dockerfile: ./Dockerfile
      target: unit_test
    env_file: .env

  localdev-flaskapp:
    image: localdev-flaskapp
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
      target: localdev
    env_file: .env
    environment:
      FLASK_APP: run.py
      FLASK_DEBUG: 1
    ports:
      - 5001:5000
    volumes:
      - .:/app
    command: flask run --host=0.0.0.0 --port=5000
