version: '3.4'

services:
  flaskdockerstarterkit:
    image: flaskdockerstarterkit
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
    volumes:
      - .:/flask_starterkit:cached
    env_file: .env
  test-runner:
    image: test-runner
    build:
      context: .
      dockerfile: ./Dockerfile.test
    env_file: .env
